services:
  # База для Django
  db_django:
    image: postgres:15-alpine
    volumes:
      - postgres_data_django:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: urfu_db
      POSTGRES_USER: urfu_user
      POSTGRES_PASSWORD: urfu_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U urfu_user -d urfu_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # База для ML сервиса
  db_ml:
    image: postgres:15-alpine
    volumes:
      - postgres_data_ml:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ml_db
      POSTGRES_USER: ml_user
      POSTGRES_PASSWORD: ml_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ml_user -d ml_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build:
      context: ./urfu
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./urfu:/app
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db_django
      DB_NAME: urfu_db
      DB_USER: urfu_user
      DB_PASSWORD: urfu_password
      DB_PORT: 5432
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost,127.0.0.1,django"
    depends_on:
      db_django:
        condition: service_healthy

  ml_service:
    build:
      context: ./ml_service
      dockerfile: Dockerfile
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host 0.0.0.0 --port 8001 --reload"
    volumes:
      - ./ml_service:/app
    ports:
      - "8001:8001"
    environment:
      DB_HOST: db_ml
      DB_NAME: ml_db
      DB_USER: ml_user
      DB_PASSWORD: ml_password
      DB_PORT: 5432
      HF_API_KEY: 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
    depends_on:
      db_ml:
        condition: service_healthy

volumes:
  postgres_data_django:
  postgres_data_ml:
